### ISSUE TITLE
yesterday's commit introduced a bug

### ISSUE THREAD

**Issue by Vinni-Cedraz** [zbirenbaum/copilot-cmp#50] opened 2023-02-26 16:52 UTC
Error detected while processing TextChangedI Autocommands for "*":
Error executing lua callback: .../nvim/site/pack/packer/start/nvim-cmp/lua/cmp/source.lua:325: attempt to call method 'com
plete' (a nil value)
stack traceback:
        .../nvim/site/pack/packer/start/nvim-cmp/lua/cmp/source.lua:325: in function 'complete'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:289: in function 'complete'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:169: in function 'callback'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:219: in function 'autoindent'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:161: in function 'on_change'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/init.lua:313: in function 'callback'
        ...ite/pack/packer/start/nvim-cmp/lua/cmp/utils/autocmd.lua:49: in function 'emit'
        ...ite/pack/packer/start/nvim-cmp/lua/cmp/utils/autocmd.lua:23: in function <...ite/pack/packer/start/nvim-cmp/lua
/cmp/utils/autocmd.lua:22>

**Comment by zbirenbaum** [comment] 2023-02-26 17:14
Can you provide any info on how to reproduce this? I haven't seen this error so far.

**Comment by jamesnaftel** [comment] 2023-03-26 19:47
I saw this when still had hrsh7th/cmp-copilot installed.  Once removed, all was well.

**Comment by zbirenbaum** [comment] 2023-04-03 06:26
Closing because this ins't reproducible and is caused by a plugin conflict

**Closed as completed** 2023-04-03 06:25 UTC
