### ISSUE TITLE
Accepting copilot suggestion puts it at the beginning of line (no indentation) 

### ISSUE THREAD

**Issue by strdr4605** [zbirenbaum/copilot-cmp#45] opened 2023-01-31 13:49 UTC
https://user-images.githubusercontent.com/16056918/215777757-445f3e49-7ca6-4c46-9bd1-9a601719c343.mov

Packer:

```lua
  use({
    "zbirenbaum/copilot-cmp",
    after = { "copilot.lua" },
    config = function()
      require("copilot_cmp").setup()
    end,
  })
  use({
    "zbirenbaum/copilot.lua",
    cmd = "Copilot",
    event = "InsertEnter",
    config = function()
      require("copilot").setup({
        suggestion = { enabled = false },
        panel = { enabled = false },
      })
    end,
  })

```

CMP config:

```lua
local cmp = require("cmp")
local luasnip = require("luasnip")

local check_backspace = function()
  local col = vim.fn.col(".") - 1
  return col == 0 or vim.fn.getline("."):sub(col, col):match("%s")
end

local has_words_before = function()
  if vim.api.nvim_buf_get_option(0, "buftype") == "prompt" then
    return false
  end
  local line, col = unpack(vim.api.nvim_win_get_cursor(0))
  return col ~= 0
      and vim.api
      .nvim_buf_get_text(0, line - 1, 0, line - 1, col, {})[1]
      :match("^%s*$")
      == nil
end

cmp.setup({
  snippet = {
    expand = function(args)
      luasnip.lsp_expand(args.body) -- For `luasnip` users.
    end,
  },
  mapping = {
    ["<C-Space>"] = cmp.mapping.complete(),
      -- config = { sources = { { name = "copilot", keyword_length = 0 } } },
    -- }),
    ["<C-e>"] = cmp.mapping({
      i = cmp.mapping.abort(),
      c = cmp.mapping.close(),
    }),
    -- Accept currently selected item. If none selected, `select` first item.
    -- Set `select` to `false` to only confirm explicitly selected items.
    ["<CR>"] = cmp.mapping.confirm({ select = true }),
    ["<Tab>"] = vim.schedule_wrap(function(fallback)
      if cmp.visible() and has_words_before() then
        cmp.select_next_item({ behavior = cmp.SelectBehavior })
      else
        fallback()
      end
    end),
    ["<S-Tab>"] = vim.schedule_wrap(function(fallback)
      if cmp.visible() and has_words_before() then
        cmp.select_prev_item({ behavior = cmp.SelectBehavior })
      else
        fallback()
      end
    end),
  },
  sources = {
    { name = "copilot", keyword_length = 0 },
    { name = "luasnip" },
    { name = "nvim_lsp" },
    { name = "nvim_lua" },
    { name = "buffer" },
    { name = "path" },
  },
})

-- Use cmdline & path source for ':' (if you enabled `native_menu`, this won't work anymore).
-- `/` cmdline setup.
cmp.setup.cmdline("/", {
  mapping = cmp.mapping.preset.cmdline(),
  sources = {
    { name = "buffer" },
  },
})
-- `:` cmdline setup.
cmp.setup.cmdline(":", {
  mapping = cmp.mapping.preset.cmdline(),
  sources = cmp.config.sources({
    { name = "path" },
  }, {
    { name = "cmdline" },
  }),
})
```

**Comment by fjchen7** [comment] 2023-02-01 06:07
Same issue here.

**Comment by georgi** [comment] 2023-02-04 10:47
same for me

**Comment by dongdongbh** [comment] 2023-02-08 06:50
Same here

**Comment by lysandroc** [comment] 2023-02-14 23:41
Try to use `cmp.SelectBehavior.Insert` instead of `cmp.SelectBehavior`

**Comment by dongdongbh** [comment] 2023-02-15 05:39
Tested both `behavior = cmp.ConfirmBehavior.Replace` and `behavior = cmp.SelectBehavior.Insert` not work.

**Comment by ttbug** [comment] 2023-02-17 07:19
fixed with   behavior = cmp.ConfirmBehavior.Replace, for me

**Comment by Vinni-Cedraz** [comment] 2023-02-21 15:35
![image](https://user-images.githubusercontent.com/92558763/220389578-51df38ba-553f-4ba9-9afe-4d01090fdc76.png)
As you can see in the picture above I was having the same issue. The first line of the suggestion was losing indentation and starting at the very beginning of the line.

`behavior = cmp.Confirmbehavior.Replace` works indeed but I had a hard time figuring out where to put it, so this here code here might be helpful to someone else.
This is where to put it:
```
cmp.setup({
	snippet = {
		expand = function() end,
	},
	mapping = cmp.mapping.preset.insert({
		["<C-right>"] = cmp.mapping.confirm({
			select = true,
			behavior = cmp.ConfirmBehavior.Replace,
		}),
```

How it looks like when fixed:

![image](https://user-images.githubusercontent.com/92558763/220393534-bf66b44a-6fd5-44c0-9b63-eeed0321a113.png)

**Comment by zbirenbaum** [comment] 2023-02-23 21:15
Did `behavior = cmp.ConfirmBehavior.Replace` work for everyone here? Indentation is extremely hard to get right, as there are so many different ways to configure indenting in neovim. If anyone is still having this issue and has confirmed they have `behavior = cmp.ConfirmBehavior.Replace` set properly in their cmp config, then please post the values of all indent related settings  including:
 - `shiftwidth`
 - `expandtab`
 - `tabstop`
 - `softtabstop`
 - `autoindent`
 - `indentexpr`
 - `smartindent`
 - `cindent`

**Comment by strdr4605** [comment] 2023-02-24 09:54
`cmp.SelectBehavior.Replace` not working for me 

https://user-images.githubusercontent.com/16056918/221146769-e7a383f8-4d87-42b1-a669-970cc95fd2e3.mov

---

all indent related settings:

```lua
vim.opt.shiftwidth = 2 -- the number of spaces inserted for each indentation
vim.opt.expandtab = true -- convert tabs to spaces
vim.opt.tabstop = 2 -- insert 2 spaces for a tab
vim.opt.smartindent = true -- make indenting smarter again
```

**Comment by dongdongbh** [comment] 2023-02-24 10:01
`cmp.SelectBehavior.Replace` not working for me
```lua
vim.opt.expandtab      = true                     
vim.opt.shiftwidth     = 2                        
vim.opt.tabstop        = 2                     
vim.opt.smarttab       = true
vim.opt.softtabstop    = 2
vim.opt.smartindent    = true            
indentexpr=nvim_treesitter#indent()
cindent=nocindent
```

**Comment by zbirenbaum** [comment] 2023-02-24 22:45
> `cmp.SelectBehavior.Replace` not working for me
> 
> ```lua
> vim.opt.expandtab      = true                     
> vim.opt.shiftwidth     = 2                        
> vim.opt.tabstop        = 2                     
> vim.opt.smarttab       = true
> vim.opt.softtabstop    = 2
> vim.opt.smartindent    = true            
> indentexpr=nvim_treesitter#indent()
> cindent=nocindent
> ```

treesitter indentation is notoriously buggy and is very likely the problem here. I would definitely turn it off as a first step if you are having issues. If it's still anything like was when I last used it, I really wouldn't ever recommend turning it on.

**Comment by dongdongbh** [comment] 2023-02-27 03:35
I disable treesitter indentation, then in a lua file, my indentexpr is `indentexpr=GetLuaIndent()`, and the problem still there; in a cpp file `indentexpr=`, and the problem persist

**Comment by thallada** [comment] 2023-03-02 18:04
Also experiencing the issue even with `indentexpr=` set and with all variations of `expandtab`, `smarttab`, `smartindent`, and `cindent` on an off. Setting `behavior = cmp.ConfirmBehavior.Replace` or `behavior = cmp.ConfirmBehavior.Insert` does not affect it either.

**Comment by danbrownlow** [comment] 2023-03-03 19:48
Thanks for that code snippet, @Vinni-Cedraz. I'm using lazyvim and adding the following under `lua/plugins/copilot.lua` solved the indentation issue for me also. Pasting it below for anyone else who is having trouble with this issue.

```
return {
  -- copilot
  {
    "zbirenbaum/copilot.lua",
    cmd = "Copilot",
    build = ":Copilot auth",
    opts = {
      suggestion = { enabled = false },
      panel = { enabled = false },
    },
  },

  -- copilot cmp source
  {
    "nvim-cmp",
    dependencies = {
      {
        "zbirenbaum/copilot-cmp",
        dependencies = "copilot.lua",
        config = function(_, opts)
          local copilot_cmp = require("copilot_cmp")
          copilot_cmp.setup(opts)
          -- attach cmp source whenever copilot attaches
          -- fixes lazy-loading issues with the copilot cmp source
          require("lazyvim.util").on_attach(function(client)
            if client.name == "copilot" then
              copilot_cmp._on_insert_enter()
            end
          end)
        end,
      },
    },
    ---@param opts cmp.ConfigSchema
    opts = function(_, opts)
      local cmp = require("cmp")
      opts.snippet = vim.tbl_extend("force", opts.snippet, {
        expand = function() end,
      })
      opts.mapping = vim.tbl_extend("force", opts.mapping, {
        ["<CR>"] = cmp.mapping.confirm({
          select = true,
          behavior = cmp.ConfirmBehavior.Replace,
        }),
      })
      opts.sources = cmp.config.sources(vim.list_extend(opts.sources, { { name = "copilot" } }))
    end,
  },
}
````

**Comment by thallada** [comment] 2023-03-03 20:07
@danbrownlow thanks for posting that snippet. Made me realize I was specifying `cmp.ConfirmBehavior.Replace` in the wrong place in my config. It needs to be on the `<CR>` mapping:

```
local cmp = require('cmp')

cmp.setup({
  ...
  mapping = cmp.mapping.preset.insert({
    ...
    ['<CR>'] = cmp.mapping.confirm({ select = true, behavior = cmp.ConfirmBehavior.Replace }),
    ...
  }),
})
```
^ adding `behavior = cmp.ConfirmBehavior.Replace` there fixes it for me, I was trying to add it to the `<Tab>` mapping before.

**Comment by folke** [comment] 2023-03-05 16:11
@danbrownlow I just pushed an update to LazyVim for the copilot extra that does **Replace** but only for the confirming a completion from the **copilot** source.

See https://github.com/LazyVim/LazyVim/commit/079d3967d03d47b95bdec10bb2621db1c4a07dce

**Comment by dongdongbh** [comment] 2023-03-06 01:49
I tried everything here and didn't solve my problem, here is my config
copilot
```lua
require("copilot").setup({
  suggestion = {
    enabled = false,
    auto_trigger = false,
  },
  filetypes = {
    markdown = true, -- overrides default
    terraform = false, -- disallow specific filetype
  },
})

require("copilot_cmp").setup {
  method = "getCompletionsCycling",
  formatters = {
    insert_text = require("copilot_cmp.format").remove_existing
  },
}
```
cmp
```lua
cmp.setup({
  snippet = {
    expand = function(args)
      luasnip.lsp_expand(args.body) -- For `luasnip` users.
    end,
  },

  mapping = cmp.mapping.preset.insert({
    ["<C-k>"] = cmp.mapping.select_prev_item(),
    ["<C-j>"] = cmp.mapping.select_next_item(),
    ["<C-b>"] = cmp.mapping(cmp.mapping.scroll_docs(-1), { "i", "c" }),
    ["<C-f>"] = cmp.mapping(cmp.mapping.scroll_docs(1), { "i", "c" }),
    ["<C-Space>"] = cmp.mapping(cmp.mapping.complete(), { "i", "c" }),
    ["<C-e>"] = cmp.mapping({
      i = cmp.mapping.abort(),
      c = cmp.mapping.close(),
    }),
    -- Accept currently selected item. If none selected, `select` first item.
    -- Set `select` to `false` to only confirm explicitly selected items.
    ['<CR>'] = cmp.mapping.confirm({ select = true, behavior = cmp.ConfirmBehavior.Replace }),
    ["<Tab>"] = cmp.mapping(function(fallback)
      -- if require("copilot.suggestion").is_visible() then
      --   require("copilot.suggestion").accept()
      if cmp.visible() and has_words_before() then
        cmp.select_next_item({ behavior = cmp.SelectBehavior.Replace })
      elseif luasnip.expandable() then
        luasnip.expand()
      elseif luasnip.expand_or_jumpable() then
        luasnip.expand_or_jump()
      elseif check_backspace() then
        fallback()
      else
        fallback()
      end
    end, {
        "i",
        "s",
      }),
    ["<S-Tab>"] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_prev_item()
      elseif luasnip.jumpable(-1) then
        luasnip.jump(-1)
      else
        fallback()
      end
    end, {
        "i",
        "s",
    }),
  }),
  formatting = {
    fields = { "kind", "abbr", "menu" },
    format = function(entry, vim_item)
      vim_item.kind = kind_icons[vim_item.kind]
      vim_item.menu = ({
        nvim_lsp = "",
        nvim_lua = "",
        luasnip = "",
        buffer = "",
        path = "",
        emoji = "",
      })[entry.source.name]
      return vim_item
    end,
  },
  sources = {
    {
      name = "copilot",
      max_item_count = 3,
      group_index = 2,
    },
    { name = "nvim_lsp" },
    { name = "neorg" },
    { name = "nvim_lua" },
    { name = "luasnip" },
    { name = "buffer" },
    { name = "path" },
  },
  sorting = {
    priority_weight = 2,
    comparators = {
      require("copilot_cmp.comparators").prioritize,
      require("copilot_cmp.comparators").score,

      -- Below is the default comparitor list and order for nvim-cmp
      cmp.config.compare.offset,
      -- cmp.config.compare.scopes, --this is commented in nvim-cmp too
      cmp.config.compare.exact,
      cmp.config.compare.score,
      cmp.config.compare.recently_used,
      cmp.config.compare.locality,
      cmp.config.compare.kind,
      cmp.config.compare.sort_text,
      cmp.config.compare.length,
      cmp.config.compare.order,
    },
  },
  -- confirm_opts = {
  --   behavior = cmp.ConfirmBehavior.Replace,
  --   select = false,
  -- },
  window = {
    completion = cmp.config.window.bordered(),
    documentation = cmp.config.window.bordered(),
  },
  experimental = {
    ghost_text = true,
  },
})
```

**Comment by dongdongbh** [comment] 2023-03-06 03:02
Oh, I fixed it by upgrading the copilot-cmp and nvim-cmp plugin, I'm not sure which upgrading fixed it.

**Comment by sqwxl** [comment] 2023-03-21 02:14
I've tried everything here, but I still have this issue.

Here's the relevant setup:

```lua
vim.opt.smartindent = true
vim.opt.breakindent = true
vim.opt.smarttab = true
vim.opt.expandtab = true
vim.opt.shiftwidth = 2
vim.opt.tabstop = 2
vim.opt.softtabstop = 2
```

```lua
local cmp_mappings = cmp.mapping.preset.insert{
      ["<C-p>"] = cmp.mapping.select_prev_item({ behavior = cmp.SelectBehavior.Select }),
      ["<C-n>"] = cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Select }),
      ["<C-u>"] = cmp.mapping.scroll_docs(-4),
      ["<C-d>"] = cmp.mapping.scroll_docs(4),
      ["<C-Space>"] = cmp.mapping.complete(),
      ["<C-e>"] = cmp.mapping.close(),
      ["<CR>"] = cmp.mapping.confirm({ behavior = cmp.ConfirmBehavior.Replace, select = true }),
      ["<Tab>"] = cmp.mapping(function(fallback)
      if cmp.visible() and has_words_before() then
        cmp.select_next_item({ behavior = cmp.SelectBehavior.Replace })
      elseif luasnip.expand_or_jumpable() then
        luasnip.expand_or_jump()
      else
        fallback() -- The fallback function sends a already mapped key. In this case, it's probably `<Tab>`.
      end
    end,
    { "i", "s" }),
      ["<S-Tab>"] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_prev_item({ behavior = cmp.SelectBehavior.Select })
      elseif luasnip.jumpable(-1) then
        luasnip.jump(-1)
      else
        fallback()
      end
    end,
    { "i", "s" }),
}
```

lazy.nvim plugin spec:
```lua
{
  "zbirenbaum/copilot-cmp",
  config = true,
  dependencies = {
    {
      "zbirenbaum/copilot.lua",
      event = "InsertEnter",
      opts = {
        suggestion = { enabled = false },
        panel = { enabled = false },
      },
    }
  }
}
```

**Comment by patricklewis** [comment] 2023-03-31 14:11
I made the update suggested by @thallada and it fixed this issue for me.

Including `behavior = cmp.ConfirmBehavior.Replace` in the `<CR>` mapping of my `nvim-cmp` configuration was all I needed to do to fix this issue.

Thanks!

**Closed as completed** 2023-09-07 10:58 UTC

**Comment by gshpychka** [comment] 2023-11-09 16:37
@zbirenbaum I see that you closed this issue, but I still have the problem with the following config:


```lua
["<CR>"] = cmp.mapping({
  i = function(fallback)
    if cmp.visible() and cmp.get_active_entry() then
      cmp.confirm({ behavior = cmp.ConfirmBehavior.Replace, select = false })
    else
      fallback()
    end
  end,
}),
```

**Comment by zhimsel** [comment] 2024-05-07 20:04
@zbirenbaum (and anyone else), I'm also seeing the same behavior, even with the most recent versions of [`copilot-cmp`](https://github.com/zbirenbaum/copilot-cmp/commit/72fbaa03695779f8349be3ac54fa8bd77eed3ee3) and [`copilot.lua`](https://github.com/zbirenbaum/copilot.lua/commit/f7612f5af4a7d7615babf43ab1e67a2d790c13a6).

Relevant bits of my config:
- [cmp mappings](https://github.com/zhimsel/dotfiles/blob/d31a55637cfd1c361f4b9b402dfcf085c3c1d845/.config/nvim/lua/zhimsel/syntax.lua#L221-L263)
- [copilot config](https://github.com/zhimsel/dotfiles/blob/d31a55637cfd1c361f4b9b402dfcf085c3c1d845/.config/nvim/lua/zhimsel/plugins/github_copilot.lua)
- [cmp source](https://github.com/zhimsel/dotfiles/blob/d31a55637cfd1c361f4b9b402dfcf085c3c1d845/.config/nvim/lua/zhimsel/syntax.lua#L151)
- Tried [disabling TreeSitter indenting](https://github.com/zhimsel/dotfiles/commit/5715ad74964d331b43e2549e16b53cf7e8bc051c) (didn't make a difference)

**Comment by xlucn** [comment] 2024-08-28 04:58
@zbirenbaum  I believe I found the reason for at least some of the cases. It's related to `shiftwidth`.

In vim/neovim, `shiftwidth=0` will make vim use the value of `tabstop`. Although I haven't written any vim/neovim plugins, it seems that the developer has to take care of the case `shiftwidth=0` if they want to use this option. Currently, if `shiftwidth=0`, the following code:
https://github.com/zbirenbaum/copilot-cmp/blob/b6e5286b3d74b04256d0a7e3bd2908eabec34b44/lua/copilot_cmp/format.lua#L91-L94
results in
```lua
user_indent = ""
indent_level = inf
```

Something like this works for me (replacing the code above):
```lua
  if user_indent == ' ' then
    local shiftwidth = vim.o.shiftwidth
    if shiftwidth == 0 then
      shiftwidth = vim.o.tabstop
    end
    user_indent = string.rep(' ', shiftwidth)
    indent_level = math.floor(indent_offset/shiftwidth)
  end
```

For those who still have the issue, if your current `shiftwidth` value is 0 (use `:set shiftwidth?` to check instead of looking into your config), and the indent is corrected after setting it to a positive value, then this must be the reason.
